### ISSUE TITLE
How to replace to testnet instead of regtest ?

### ISSUE THREAD

**Issue by BlockchainHe** [bitlightlabs/bitlight-local-env-public#4]
This code use docker to build local regtest environment.

But I want to know How it can connect to public regtest or testnet.

**Comment by bitlightlabs-dev** [comment]
Regtest is a network designed solely to be private and for testing only. You can create a private regtest network and do testing and experimentation with it. It is not a public network and has no peers for you to connect to.

https://bitcoin.stackexchange.com/questions/70156/difference-between-regtest-and-testnet
